WebApp/Areas/Admin/Controllers/MenuCategoryController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Mappers;
using BLL.App.DTO.Menu;
using Contracts.BLL.App;
using Domain.App.Identity;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Company Admin")]
    public class MenuCategoryController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        

        public MenuCategoryController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, MenuId")] MenuCategoryData category)
        {
            var companyId = await _bll.Menus.GetMenuCompanyId(category.MenuId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                NotFound();
            }
            
            if (ModelState.IsValid)
            {
                var menuCategory = MenuCategoryMapper.MapToRegBLL(category);
                menuCategory.Position = _bll.MenuCategories.GetCategoryCountInMenu(menuCategory.MenuId);
                _bll.MenuCategories.Add(menuCategory);
                await _bll.SaveChangesAsync();
            }

            return RedirectToAction(nameof(MenuController.Edit), "Menu",new {id = category.MenuId});
        }

        public async Task<IActionResult> Edit(int? id, int companyId, int menuId)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var categoryCompanyId = await _bll.MenuCategories.GetCategoryCompanyId(id.Value);

            if (!await User.DoesUserHaveAuthorityToEdit(categoryCompanyId, _userManager))
            {
                return NotFound();
            }

            var menuCategory = await _bll.MenuCategories.FirstOrDefaultEditAsyncBLL(id.Value);

            if (menuCategory == null)
            {
                return NotFound();
            }
            
            menuCategory.MenuId = menuId;
            
            return View(menuCategory);

        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, MenuId")] MenuCategoryData category)
        {
            if (id != category.Id)
            {
                return BadRequest();
            }
           
            var categoryCompanyId = await _bll.MenuCategories.GetCategoryCompanyId(id);

            if (!await User.DoesUserHaveAuthorityToEdit(categoryCompanyId, _userManager))
            {
                return NotFound();
            }
            
            var menuCategory = await _bll.MenuCategories.FirstOrDefaultEditAsyncBLL(id);
            
            if (menuCategory == null)
            {
                return NotFound();
            }

            menuCategory.Name = category.Name;
            _bll.MenuCategories.Update(MenuCategoryMapper.MapToRegBLL(menuCategory));
            await _bll.SaveChangesAsync();

            return RedirectToAction(nameof(MenuController.Edit), "Menu",new {id = category.MenuId});
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            

            var menu = await _bll.MenuCategories.FirstOrDefaultEditAsyncBLL(id.Value);
            if (menu == null)
            {
                return NotFound();
            }

            var companyId = await _bll.MenuCategories.GetCategoryCompanyId(id.Value);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }


            return View(menu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!await _bll.MenuCategories.ExistsAsync(id))
            {
                return NotFound();
            }

            var companyId = await _bll.MenuCategories.GetCategoryCompanyId(id);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            var menuId = await _bll.MenuCategories.GetCategoryMenuId(id);

            await _bll.MenuCategories.MoveCategoriesUpWhenDelete(id);

            await _bll.MenuCategories.RemoveAsync(id, default);
            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(MenuController.Edit), "Menu",new {id = menuId});
        }
    }
}

WebApp/Areas/Admin/Controllers/ProductController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Mappers;
using BLL.App.DTO.Product;
using Contracts.BLL.App;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Company Admin")]
    public class ProductController : Controller
    {
        private readonly IAppBLL _bll;

        private readonly UserManager<Domain.App.Identity.AppUser> _userManager;
        
        public ProductController(UserManager<Domain.App.Identity.AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }
        
        public async Task<IActionResult> Create(int menuId)
        {
            if (!await _bll.Menus.ExistsAsync(menuId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.Menus.GetMenuCompanyId(menuId);

            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            var product = new ProductCreate
            {
                MenuId = menuId,
                MenuCategories = await _bll.MenuCategories.GetAllMenuCategoriesOnlyNameBLL(menuId)
            };
            
            return View(product);
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(int menuId, [Bind("Name,IsAlwaysPurchasable,Price,MenuCategoryId,Picture,Description")] ProductData productData)
        {
            var companyId = await _bll.MenuCategories.GetCategoryCompanyId(productData.MenuCategoryId);

            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var regBLLProduct = ProductMapper.MapToRegBLL(productData);
                regBLLProduct.Position = _bll.Products.GetProductCountInCategory(regBLLProduct.MenuCategoryId);
                
                _bll.Products.Add(regBLLProduct);
                await _bll.SaveChangesAsync();
                
                var id = _bll.Products.GetUpdatedEntityAfterSaveChanges(regBLLProduct).Id;
                return RedirectToAction(nameof(Edit), new{id});
            }
            
            return RedirectToAction(nameof(Create), new {menuId});
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            Console.WriteLine(id);
            if (id == null)
            {
                return NotFound();
            }

            var product = await _bll.Products.FirstOrDefaultEditAsyncBLL(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            var companyId = await _bll.Products.GetProductCompanyId(id.Value);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            return View(product);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int menuId,
            [Bind("Id,Name,IsAlwaysPurchasable,Price,MenuCategoryId,Picture,Description")] ProductData productData)
        {
            var companyId = await _bll.Products.GetProductCompanyId(productData.Id);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            var dbProduct = await _bll.Products.FirstOrDefaultAsync(productData.Id);
            if (dbProduct == null)
            {
                return NotFound();
            }
           
            if (ModelState.IsValid)
            {
                dbProduct.Name = productData.Name;
                dbProduct.IsAlwaysPurchasable = productData.IsAlwaysPurchasable;
                dbProduct.Price = productData.Price;
                dbProduct.Picture = productData.Picture;
                dbProduct.Description = productData.Description;
                
                if (dbProduct.MenuCategoryId != productData.MenuCategoryId)
                {
                    if (!await _bll.MenuCategories.ExistsAsync(productData.MenuCategoryId))
                    {
                        return NotFound();
                    }
                    dbProduct.MenuCategoryId = productData.MenuCategoryId;
                    dbProduct.Position = _bll.Products.GetProductCountInCategory(productData.MenuCategoryId);
                    await _bll.ProductsSubCategories.MoveSubCategoriesUpWhenDelete(dbProduct.Id);
                }

                _bll.Products.Update(dbProduct);
                await _bll.SaveChangesAsync();
            }

            var productEdit = ProductMapper.MapToEditBLL(productData);
            productEdit.MenuCategories = await _bll.MenuCategories.GetAllMenuCategoriesOnlyNameBLL(menuId);
            productEdit.MenuId = menuId;

            return View(productEdit);
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _bll.Products
                .FirstOrDefaultEditAsyncBLL(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            var companyId = await _bll.Products.GetProductCompanyId(id.Value);

            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            return View(product);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!await _bll.Products.ExistsAsync(id))
            {
                return NotFound();
            }

            var companyId = await _bll.Products.GetProductCompanyId(id);

            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            var menuId = await _bll.Products.GetProductMenuId(id);
            
            await _bll.Products.MoveProductsUpWhenDelete(id);

            await _bll.Products.RemoveAsync(id, default);
            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(Edit), "Menu", new {id = menuId});
        }
        
        public async Task<IActionResult> MoveProduct(int productId, int menuId, bool moveUp)
        {
            if (!await _bll.Products.ExistsAsync(productId))
            {
                return NotFound();
            }
            
            var categoryCompanyId = await _bll.Products.GetProductCompanyId(productId);
            if (!await User.DoesUserHaveAuthorityToEdit(categoryCompanyId, _userManager))
            {
                return NotFound();
            }
         
            var result = await _bll.Products.ChangeProductPosition(productId, moveUp);
            if (!result)
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Edit), "Menu", new {id = menuId});
        }
    }
}

WebApp/Areas/Admin/Views/Menu/Create.cshtml
@model BLL.App.DTO.Menu.MenuData

@{
    ViewData["Title"] = "Create";
}

<h1>@Resources.CommonCrud.Create</h1>

<h4>@Resources.BLL.App.DTO.Restaurant.RestaurantString</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="CompanyId" type="hidden">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Resources.CommonCrud.Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Resources.CommonCrud.BackToList</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Areas/Admin/Views/Menu/Delete.cshtml
@model BLL.App.DTO.Menu.Menu

@{
    ViewData["Title"] = "Delete";
}

<h1>@Resources.CommonCrud.Delete</h1>

<h3>@Resources.CommonCrud.DeleteAreYouSureMessage</h3>
<div>
    <h4>@Resources.BLL.App.DTO.Menu.MenuString</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Resources.CommonCrud.Delete" class="btn btn-danger" /> |
        <a asp-action="Index">@Resources.CommonCrud.BackToList</a>
    </form>
</div>

WebApp/Areas/Admin/Views/Menu/Edit.cshtml
@using BLL.App.DTO.Menu
@model BLL.App.DTO.Menu.MenuEdit


<h1>@Resources.CommonCrud.Edit</h1>

<h4>@Resources.BLL.App.DTO.Menu.MenuString</h4>
<hr />

<div class="row">
    <div class="col-md">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="Edit">
            <input type="hidden" asp-for="CompanyId">
            <input type="hidden" asp-for="Id"/>
            <div class="col-md">
                <label asp-for="Name" name="name" class="control-label"></label>
                <input asp-for="Name" name="name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="col-md">
                <input value="@Resources.CommonCrud.Save" type="submit" class="btn btn-primary"/>
                <a asp-action="Index">@Resources.CommonCrud.BackToList</a>
            </div>
        </form>
    </div>
       
    <div class="col-md">
        @if (Model.CompanyMenus != null)
        {
            <form asp-action="CopyOtherMenuItems">
                <input type="hidden" asp-for="CompanyId">
                <input type="hidden" asp-for="Id" name="currentMenuId"/>
                <div class="col-md">
                    <label for="otherMenuId">@Resources.Areas.Admin.Menu.CopyMenusItems</label>
                    <select id="otherMenuId" name="otherMenuId">
                        @foreach (var menu in Model.CompanyMenus)
                        {
                            <option value="@menu.Id">@menu.Name</option>
                        }
                    </select>
                </div>
                <div class="col-md">
                    <input value="@Resources.CommonCrud.Add" type="submit" class="btn btn-primary"/>
                </div>
            </form>
        }
    </div>
</div>
<hr>
<div class="row">
    <div class="col-4">
        @if(Model.MenuCategories != null){
            @for (var i = 0; i < Model.MenuCategories.Count; i++)
            {
                <div @Html.Raw(Model.CurrentCategory?.Id.Equals(Model.MenuCategories[i].Id) ?? false
                         ? "style='background-color: #EEEEED'"
                         : "")>
                    <a asp-action="Edit" asp-route-id="@Model.Id" asp-route-currentCategoryId="@Model.MenuCategories[i].Id">@Model.MenuCategories[i].Name</a>
                    <a asp-controller="MenuCategory" asp-action="Edit" asp-route-id="@Model.MenuCategories[i].Id"
                       asp-route-menuId="@Model.Id">@Resources.CommonCrud.Edit</a> |
                    <a asp-controller="MenuCategory" asp-action="Delete" asp-route-id="@Model.MenuCategories[i].Id"
                       asp-route-menuId="@Model.Id">@Resources.CommonCrud.Delete</a> 
                    <span @Html.Raw(i.Equals(0) ? "hidden='hidden'" : "")>
                        | 
                        <a asp-action="MoveCategory" asp-route-menuId="@Model.Id" asp-route-categoryId="@Model.MenuCategories[i].Id" asp-route-moveUp="true">
                            @Resources.CommonCrud.Up
                        </a>
                    </span>
                    <span @Html.Raw(i.Equals(Model.MenuCategories.Count - 1) ? "hidden='hidden'" : "")>
                        |
                        <a asp-action="MoveCategory" asp-route-menuId="@Model.Id" asp-route-categoryId="@Model.MenuCategories[i].Id" asp-route-moveUp="false">
                            @Resources.CommonCrud.Down
                        </a>
                    </span>
                </div>
            }
        }
        <hr>
        <div>
            <form method="post">
                <label asp-for="Name" >@Resources.BLL.App.DTO.MenuCategory.CategoryString @Resources.BLL.App.DTO.Common.Name</label>
                <br>
                <input asp-for="Name" value="">
                <input type="hidden" asp-for="Id" name="MenuId">
                <input type="submit" class="btn btn-primary" value="@Resources.CommonCrud.Create" 
                       asp-controller="MenuCategory" asp-action="Create"/>
            </form>
        </div>
        
    </div>
    <div class="col-8">
        @if (Model.MenuCategories!.Count> 0)
        {
            <div style="text-align: right">
                <a asp-controller="Product" asp-action="Create" asp-route-menuId="@Model.Id">@Resources.CommonCrud.CreateNew @Resources.BLL.App.DTO.Product.ProductString</a>
            </div>
        }
        @if (Model.CurrentCategory?.Products != null)
        {
            @for (var i = 0; i < Model.CurrentCategory.Products.Count; i++)
            {
                <div>
                    @Html.DisplayFor(x => Model.CurrentCategory.Products[i].Name)
                    <span @Html.Raw(i.Equals(0) ? "hidden='hidden'" : "")>
                        |
                        <a asp-controller="Product" asp-action="MoveProduct" asp-route-menuId="@Model.Id"
                           asp-route-productId="@Model.CurrentCategory.Products[i].Id" asp-route-moveUp="true">
                            @Resources.CommonCrud.Up
                        </a>
                    </span>
                    <span @Html.Raw(i.Equals(Model.CurrentCategory.Products.Count - 1) ? "hidden='hidden'" : "")>
                        |
                        <a asp-controller="Product" asp-action="MoveProduct" asp-route-menuId="@Model.Id"
                           asp-route-productId="@Model.CurrentCategory.Products[i].Id" asp-route-moveUp="false">
                            @Resources.CommonCrud.Down
                        </a>
                    </span>
                    |
                    <a asp-controller="Product" asp-action="Edit"
                       asp-route-id="@Model.CurrentCategory.Products[i].Id">@Resources.CommonCrud.Edit</a> |
                    <a asp-controller="Product" asp-action="Delete"
                       asp-route-id="@Model.CurrentCategory.Products[i].Id">@Resources.CommonCrud.Delete</a>

                    @Html.DisplayFor(x => Model.CurrentCategory.Products[i].Price)@Resources.CommonCrud.Currency
                    <dl class="row">
                        <dt class = "col-sm-2">
                            @Html.DisplayNameFor(model => Model.CurrentCategory.Products[i].Picture)
                        </dt>
                        <dd class = "col-sm-10">
                            @Html.DisplayFor(model => Model.CurrentCategory.Products[i].Picture)
                        </dd> 
                        <dt class = "col-sm-2">
                            @Html.DisplayNameFor(model => Model.CurrentCategory.Products[i].IsAlwaysPurchasable)
                        </dt>
                        <dd class = "col-sm-10">
                            @(Model.CurrentCategory.Products[i].IsAlwaysPurchasable ? Resources.CommonCrud.Yes : Resources.CommonCrud.No)
                        </dd>
                        <dd class = "col-sm-10">
                            @Html.DisplayFor(model => Model.CurrentCategory.Products[i].Description)
                        </dd>
                    </dl>
                </div>
                <hr>
            }
        }
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Areas/Admin/Views/Menu/Index.cshtml
@model IEnumerable<BLL.App.DTO.Menu.MenuIndex>

@{
    ViewData["Title"] = "Index";
}

<h1>@Resources.BLL.App.DTO.Menu.Menus</h1>

<p>
    <a asp-action="Create">@Resources.CommonCrud.CreateNew</a>
</p>
<table class="table">
    <thead>
    <tr>
    <th>
        @Html.DisplayNameFor(model => model.Name)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CompanyName)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.RestaurantsWithTheMenu)
    </th>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @if (item.RestaurantsWithTheMenu != null)
                {
                    @foreach (var restaurant in item.RestaurantsWithTheMenu)
                    {
                        @Html.DisplayFor(restaurant2 => restaurant.Name)
                        <br>
                    }
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">@Resources.CommonCrud.Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">@Resources.CommonCrud.Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>