WebApp/Areas/Worker/Controllers/OrderController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Domain.App.Identity;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.Worker.Controllers
{
    [Area("Worker")]
    [Authorize(Roles = "Restaurant Worker")]
    public class OrderController: Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        

        public OrderController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }
        
        public async Task<IActionResult> Index(int restaurantId)
        {
            if (!await _bll.Restaurants.ExistsAsync(restaurantId))
            {
                return NotFound();
            }

            var companyId = await _bll.Restaurants.GetRestaurantCompanyId(restaurantId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            var orders = await _bll.Orders.GetWorkerOrderView(restaurantId, false);

            return View(orders);
        }
        
        public async Task<IActionResult> Ready(int restaurantId)
        {
            if (!await _bll.Restaurants.ExistsAsync(restaurantId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.Restaurants.GetRestaurantCompanyId(restaurantId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            var orders = await _bll.Orders.GetWorkerOrderView(restaurantId, true);
            
            return View(orders);
        }
        
        public async Task<IActionResult> Completed(int restaurantId)
        {
            if (!await _bll.Restaurants.ExistsAsync(restaurantId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.Restaurants.GetRestaurantCompanyId(restaurantId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            var orders = await _bll.ArchivedOrders.GetWorkerOrderView(restaurantId);
            
            return View(orders);
        }
        
        public async Task<IActionResult> ChangeCompleteTime(int orderId, string newCompleteTime)
        {
            if (!await _bll.Orders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.Orders.GetCompanyId(orderId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            var restaurantId = await _bll.Orders.GetRestaurantId(orderId);
            
            if (!DateTime.TryParse(newCompleteTime, out var newCompleteDateTime))
            {
                return RedirectToAction(nameof(Index), new {restaurantId});
            }
            
            if (!await _bll.Orders.ChangeOrderCompleteTime(orderId, newCompleteDateTime))
            {
                return NotFound();
            }
            
            return RedirectToAction(nameof(Index), new {restaurantId});
        }
        
        public async Task<IActionResult> ChangeOrderToReady(int orderId)
        {
            if (!await _bll.Orders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.Orders.GetCompanyId(orderId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            if (!await _bll.Orders.ChangeOrderToReady(orderId))
            {
                return NotFound();
            }
            
            var restaurantId = await _bll.Orders.GetRestaurantId(orderId);
            
            return RedirectToAction(nameof(Index), new {restaurantId});
        }
        
        public async Task<IActionResult> ArchiveOrder(int orderId)
        {
            if (!await _bll.Orders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.Orders.GetCompanyId(orderId);
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            var restaurantId = await _bll.Orders.GetRestaurantId(orderId);
            
            if (!await _bll.Orders.ArchiveOrder(orderId))
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Ready), new {restaurantId});
        }
        
        public async Task<IActionResult> AddCommentToArchivedOrder(int orderId, string comment)
        {
            if (!await _bll.ArchivedOrders.ExistsAsync(orderId))
            {
                return NotFound();
            }

            var companyId = await _bll.ArchivedOrders.GetCompanyId(orderId);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            await _bll.ArchivedOrders.AddCommentToOrder(orderId, comment, false);
            
            var restaurantId = await _bll.ArchivedOrders.GetRestaurantId(orderId);

            return RedirectToAction(nameof(Completed), new {restaurantId});
        }
    }
    
}

WebApp/Controllers/OrderController.cs
#pragma warning disable 1591
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Domain.App.Identity;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
      
        private readonly IAppBLL _bll;
        private UserManager<AppUser> _userManager;
        
        public OrderController(IAppBLL bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            var orders = await _bll.Orders.GetAllActiveClientAsyncBLL(User.GetUserId()!.Value);

            return View(orders);
        }
        
        public async Task<IActionResult> Completed()
        {
            var orders = await _bll.ArchivedOrders.GetAllCompletedOrdersClientAsyncBLL(User.GetUserId()!.Value);

            return View(orders);
        }
        
        public async Task<IActionResult> AddCommentToArchivedOrder(int orderId, string comment)
        {
            if (!await _bll.ArchivedOrders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }

            await _bll.ArchivedOrders.AddCommentToOrder(orderId, comment, true);

            return RedirectToAction(nameof(Completed));
        }
        
        public async Task<IActionResult> AddRatingToOrder(int orderId, int rating)
        {
            if (rating < 1 || rating > 5)
            {
                return BadRequest();
            }
            
            if (!await _bll.ArchivedOrders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }

            await _bll.ArchivedOrders.AddRatingToOrder(orderId, rating);
            
            return RedirectToAction(nameof(Completed));
        }
    }
}

WebApp/Controllers/RestaurantsController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Product;
using Contracts.BLL.App;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly IAppBLL _bll;

        public RestaurantsController(IAppBLL bll)
        {
            _bll = bll;
        }
        
        public async Task<IActionResult> Index()
        {
            var restaurantViewModel = await _bll.Restaurants.GetAllRestaurantViewModel(User.GetUserId());
            
            return View(restaurantViewModel);
        }
        
        public async Task<IActionResult> Restaurant(int id, int? currentCategoryPosition)
        {
            var restaurant = await _bll.Restaurants.FirstOrDefaultClientAsyncBLL(id, currentCategoryPosition);
            if (restaurant == null)
            {
                return NotFound();
            }
            
            return View(restaurant);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddRestaurantToUserFavorites(int id)
        {
            if (await _bll.AppUsers.GetUserCompanyId(User.GetUserId()!.Value) != null)
            {
                return BadRequest();
            }

            if (!await _bll.Restaurants.ExistsAsync(id))
            {
                return NotFound();
            }
            
            if (!await _bll.AppUsers.AddUserFavoriteRestaurant(id, User.GetUserId()!.Value))
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Restaurant), new {id});
        }
        
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> RemoveRestaurantFromUserFavorites(int id)
        {
            if (await _bll.AppUsers.GetUserCompanyId(User.GetUserId()!.Value) != null)
            {
                return BadRequest();
            }

            if (!await _bll.Restaurants.ExistsAsync(id))
            {
                return NotFound();
            }
            
            if (!await _bll.AppUsers.RemoveUserFavoriteRestaurant(id, User.GetUserId()!.Value))
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Restaurant), new {id});
        }
        
        [HttpGet]
        public async Task<IActionResult> Product(int restaurantId, int productId)
        {
            var product = await _bll.Products.FirstOrDefaultClientAsyncBLL(productId);
            if (product == null)
            {
                return NotFound();
            }

            product.RestaurantId = restaurantId;
            
            return View(product);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddProductToOrder(int restaurantId, int productId, int amount, 
            [Bind("subCategory0")] int[] subCategory0, [Bind("subCategory1")] int[] subCategory1,
            [Bind("subCategory2")] int[] subCategory2, [Bind("subCategory3")] int[] subCategory3,
            [Bind("subCategory4")] int[] subCategory4)
        {
            
            var userId = User.GetUserId()!.Value;
            if (await _bll.AppUsers.GetUserCompanyId(userId) != null)
            {
                return BadRequest();
            }

            if (!await _bll.Products.ExistsAsync(productId))
            {
                return NotFound();
            }
            
            if (!await _bll.Restaurants.ExistsAsync(restaurantId))
            {
                return NotFound();
            }

            if (amount < 1)
            {
                return BadRequest();
            }

            if (!await _bll.Restaurants.IsRestaurantOpenById(restaurantId))
            {
                return BadRequest();
            }
            
            // if (!await _bll.Orders.IsUserBasketEmptyOrFromSameRestaurant(userId, restaurantId))
            // {
            //     return BadRequest();
            // }

            var subProductsIds = _bll.Orders.AddSubProductIdsToOneArray(subCategory0, subCategory1,
                subCategory2, subCategory3, subCategory4);
            var errors = await _bll.Orders.AddProductToOrder(userId, productId, restaurantId,amount,subProductsIds);

            if (errors != null)
            {
                return BadRequest(errors);
            }
            Console.WriteLine(errors ?? "errors on null");
            
            return RedirectToAction(nameof(Product), new {restaurantId, productId});
        }
    }
}

WebApp/Views/Order/Completed.cshtml
@using BLL.App.DTO.Archive
@using Domain.App
@model List<BLL.App.DTO.Archive.ArchivedOrderClient>

<h4>@Resources.Views.Shared._Layout.ActiveOrders</h4>
<hr>
<div class="container">
  
    @foreach (var order in Model)
    {
        <a asp-controller="Restaurants" asp-action="Restaurant" asp-route-id="@order.RestaurantId">
            <h5>@order.RestaurantName</h5>
        </a>
        <div style="background-color: #1e7e34" @Html.Raw(order.IsReady ? "" : "hidden='hidden'")>
            @Resources.Views.Order.Index.OrderIsReady
        </div>
        <div>

            @Html.DisplayNameFor(x => order.SubmitTime):
            @order.SubmitTime.ToString("HH:mm")
            |
            @Html.DisplayNameFor(x => order.CompletedBy):
            @order.CompletedBy.ToString("HH:mm")
        </div>
        @foreach (var product in order.ProductsInOrder)
        {
            <div>
                <h6>@Html.DisplayFor(x => product.Name)</h6>
                @for (var i = 0; i < product.SubProducts?.Count; i++)
                {
                    var subProduct = product.SubProducts[i];

                    <div>
                        @if (i == 0 || product.SubProducts[i - 1].SubCategoryName != subProduct.SubCategoryName)
                        {
                            <div>
                                <h6>@Html.DisplayFor(x => subProduct.SubCategoryName):</h6>
                            </div>

                        }
                        @Html.DisplayFor(x => subProduct.Name)
                        @if (subProduct.Price != 0)
                        {
                            <text> - @Html.DisplayFor(x => subProduct.Price)@Resources.CommonCrud.Currency</text>
                        }
                    </div>
                }
                <div style="text-align: right">

                    <div>
                        @Html.DisplayNameFor(x => product.OneProductPrice):
                        @Html.DisplayFor(x => product.OneProductPrice)@Resources.CommonCrud.Currency
                    </div>
                    <div>
                        @Html.DisplayNameFor(x => product.Amount):
                        @Html.DisplayFor(x => product.Amount)
                    </div>
                </div>
            </div>
            <hr>
        }
        <div @Html.Raw(order.CustomerComment == null ? "hidden='hidden'" : "")>
            @Html.DisplayNameFor(x => order.CustomerComment):
            <br>
            @Html.DisplayFor(x => order.CustomerComment)
        </div>
        <div>
            <form method="post">
                @Html.DisplayNameFor(x => order.OrderRating)
                <label for="1">1</label>
                <input type="radio" name="rating" id="1" value="1" @Html.Raw(order.OrderRating == 1 ? "checked='checked'" : "")>
                <label for="2">2</label>
                <input type="radio" name="rating" id="2" value="2" @Html.Raw(order.OrderRating == 2 ? "checked='checked'" : "")>
                <label for="3">3</label>
                <input type="radio" name="rating" id="3" value="3" @Html.Raw(order.OrderRating == 3 ? "checked='checked'" : "")>
                <label for="4">4</label>
                <input type="radio" name="rating" id="4" value="4" @Html.Raw(order.OrderRating == 4 ? "checked='checked'" : "")>
                <label for="5">5</label>
                <input type="radio" name="rating" id="5" value="5" @Html.Raw(order.OrderRating == 5 ? "checked='checked'" : "")>
                <br>
                <input type="submit" class="btn btn-primary" value="@Resources.CommonCrud.Save" 
                       asp-action="AddRatingToOrder" asp-route-orderId="@order.Id">
            </form>
        </div>
        <div>
            <form method="post">
                <label for="comment">@Html.DisplayNameFor(x => order.CustomerOrderReviewComment):</label>
                <textarea id="comment" name="comment" rows="4" cols="50">@order.CustomerOrderReviewComment</textarea>
                <input type="submit" class="btn btn-primary" value="@Resources.CommonCrud.Save" 
                       asp-action="AddCommentToArchivedOrder" asp-route-orderId="@order.Id">
            </form>
        </div>
          
        <div style="text-align: right">
            @if (order.AmountPaid < order.FoodCost)
            {
                <div>@Resources.Views.Order.Index.PayInRestaurant</div>
            }
            @Resources.CommonCrud.OrderTotalCost:
            @Html.DisplayFor(x => order.FoodCost)@Resources.CommonCrud.Currency
        </div>
        <hr>
    }
</div>

WebApp/Views/Order/Index.cshtml
@using BLL.App.DTO.Order
@model List<BLL.App.DTO.Order.OrderClient>

<h4>@Resources.Views.Shared._Layout.ActiveOrders</h4>
<hr>
<div class="container">
  
    @foreach (var order in Model ?? new List<OrderClient>())
    {
        <a asp-controller="Restaurants" asp-action="Restaurant" asp-route-id="@order.RestaurantId">
            <h5>@order.RestaurantName</h5>
        </a>
        <div style="background-color: #1e7e34" @Html.Raw(order.IsReady ? "" : "hidden='hidden'")>
            @Resources.Views.Order.Index.OrderIsReady
        </div>
        <div>

            @Html.DisplayNameFor(x => order.SubmitTime):
            @order.SubmitTime.ToString("HH:mm")
            |
            @Html.DisplayNameFor(x => order.CompletedBy):
            @order.CompletedBy.ToString("HH:mm")
        </div>
        @foreach (var product in order.ProductsInOrder)
        {
            <div>
                <h6>@Html.DisplayFor(x => product.Name)</h6>
                @for (var i = 0; i < product.SubProducts?.Count; i++)
                {
                    var subProduct = product.SubProducts[i];

                    <div>
                        @if (i == 0 || product.SubProducts[i - 1].SubCategoryName != subProduct.SubCategoryName)
                        {
                            <div>
                                <h6>@Html.DisplayFor(x => subProduct.SubCategoryName):</h6>
                            </div>
                        }
                           
                        @Html.DisplayFor(x => subProduct.Name)
                        @if (subProduct.Price != 0)
                        {
                            <text> - @Html.DisplayFor(x => subProduct.Price)@Resources.CommonCrud.Currency</text>
                        }
                    </div>
                }
                <div style="text-align: right">
                    <div>
                        @Html.DisplayNameFor(x => product.OneProductPrice):
                        @Html.DisplayFor(x => product.OneProductPrice)@Resources.CommonCrud.Currency
                    </div>
                    <div>
                        @Html.DisplayNameFor(x => product.Amount):
                        @Html.DisplayFor(x => product.Amount)
                    </div>
                </div>
            </div>
            <hr>
        }
        <div @Html.Raw(order.CustomerComment == null ? "hidden='hidden'" : "")>
            @Html.DisplayNameFor(x => order.CustomerComment):
            <br>
            @Html.DisplayFor(x => order.CustomerComment)
        </div>
        <div style="text-align: right">
            @if (order.AmountPaid < order.FoodCost)
            {
                <div>@Resources.Views.Order.Index.PayInRestaurant</div>
            }
            @Resources.CommonCrud.OrderTotalCost:
            @Html.DisplayFor(x => order.FoodCost)@Resources.CommonCrud.Currency
        </div>
        <hr>
    }
</div>