WebApp/Areas/Admin/Controllers/MenuController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Mappers;
using BLL.App.DTO.Menu;
using Contracts.BLL.App;
using Domain.App.Identity;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Company Admin")]
    public class MenuController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;

        public MenuController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _bll.Menus.GetAllIndexASyncBLL(await _bll.AppUsers.GetUserCompanyId(User.GetUserId()!.Value)));
        }
        

        [Authorize(Roles = "Company Admin")]
        public async Task<IActionResult> Create()
        {
            var newMenu = new MenuData
            {
                CompanyId = (await _bll.AppUsers.GetUserCompanyId(User.GetUserId()!.Value))!.Value
            };
            return View(newMenu);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,CompanyId")] MenuData menu)
        {
            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                _bll.Menus.Add(MenuMapper.MapToRegBLL(menu));
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(menu);
        }

        public async Task<IActionResult> Edit(int? id, int? currentCategoryId)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            if (currentCategoryId != null && !await _bll.MenuCategories.ExistsAsync(currentCategoryId.Value))
            {
                return NotFound();
            }

            var menu = await _bll.Menus.FirstOrDefaultEditAsyncBLL(id.Value, currentCategoryId);
         
            if (menu == null)
            {
                return NotFound();
            }

            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }
            
            return View(menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int? currentCategoryId, string name)
        {
            var menu = await _bll.Menus.FirstOrDefaultAsync(id);

            if (menu == null)
            {
                return NotFound();
            }

            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }

            menu.Name = name;
            _bll.Menus.Update(menu);
            await _bll.SaveChangesAsync();

            return RedirectToAction(nameof(Edit), new {id, currentCategoryId});
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var menu = await _bll.Menus.FirstOrDefaultAsync(id.Value);
            if (menu == null)
            {
                return NotFound();
            }
            
            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }


            return View(menu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var menu = await _bll.Menus.FirstOrDefaultAsync(id);
            if (menu == null)
            {
                return NotFound();
            }

            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }

            _bll.Menus.Remove(menu);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> MoveCategory(int categoryId, int menuId, bool moveUp)
        {
            if (!await _bll.MenuCategories.ExistsAsync(categoryId))
            {
                return NotFound();
            }
            var categoryCompanyId = await _bll.MenuCategories.GetCategoryCompanyId(categoryId);
            if (!await User.DoesUserHaveAuthorityToEdit(categoryCompanyId, _userManager))
            {
                return NotFound();
            }
         
            var result = await _bll.MenuCategories.ChangeCategoryPosition(categoryId, moveUp);
            if (!result)
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Edit), new {id = menuId});

        }
        
        public async Task<IActionResult> CopyOtherMenuItems(int currentMenuId, int otherMenuId)
        {
            if (!await _bll.Menus.ExistsAsync(currentMenuId) && !await _bll.Menus.ExistsAsync(otherMenuId))
            {
                return NotFound();
            }
            
            var menuCompanyId = await _bll.Menus.GetMenuCompanyId(currentMenuId);
            var otherMenuCompanyId = await _bll.Menus.GetMenuCompanyId(otherMenuId);
            if (menuCompanyId != otherMenuCompanyId || !await User.DoesUserHaveAuthorityToEdit(menuCompanyId, _userManager))
            {
                return NotFound();
            }

            await _bll.Menus.CopyMenuItemsToOtherMenu(currentMenuId, otherMenuId);
            
            return RedirectToAction(nameof(Edit), new {id = currentMenuId});
        }
    }
}

WebApp/Areas/Admin/Controllers/SubProductController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Mappers;
using BLL.App.DTO.Product;
using Contracts.BLL.App;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Company Admin")]
    public class SubProductController : Controller
    {
        private readonly IAppBLL _bll;

        private readonly UserManager<Domain.App.Identity.AppUser> _userManager;
        
        public SubProductController(UserManager<Domain.App.Identity.AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }
        
        public async Task<IActionResult> Create(int subCategoryId)
        {
            
            if (!await _bll.ProductsSubCategories.ExistsAsync(subCategoryId))
            {
                return NotFound();
            }
            
            var companyId = await _bll.ProductsSubCategories.GetSubCategoryCompanyId(subCategoryId);

            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            var productId = await _bll.ProductsSubCategories.GetProductId(subCategoryId);

            var subProduct = new ProductsSubCategoryProductData
            {
                ProductsSubCategoryId = subCategoryId,
                ProductId = productId
            };
            
            return View(subProduct);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Name,ProductId,ProductsSubCategoryId,Price,IsSelectedOnDefault,Description")]
            ProductsSubCategoryProductData subProductData)
        {
            foreach (var state in ModelState)
            {
                Console.WriteLine(state.Key + state.Value.Errors.Count);
            }
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var productCompanyId = await _bll.Products.GetProductCompanyId(subProductData.ProductId);
            var subCategoryCompanyId =
                await _bll.ProductsSubCategories.GetSubCategoryCompanyId(subProductData.ProductsSubCategoryId);

            if (productCompanyId != subCategoryCompanyId || !await User.DoesUserHaveAuthorityToEdit(productCompanyId, _userManager))
            {
                return Unauthorized();
            }


            var subProduct = ProductsSubCategoryProductMapper.MapToRegBLL(subProductData);
            subProduct.Position = _bll.ProductsSubCategoryProducts
                .GetProductSubCategoryProductCountInSubCategory(subProductData.ProductsSubCategoryId);
            
            _bll.ProductsSubCategoryProducts.Add(subProduct);
            await _bll.SaveChangesAsync();

            return RedirectToAction(nameof(Edit), "Product", new {id = subProductData.ProductId});
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyId = await _bll.ProductsSubCategoryProducts.GetProductsSubCategoryProductCompanyId(id.Value);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            
            var subProduct = await _bll.ProductsSubCategoryProducts.FirstOrDefaultEditAsyncBLL(id.Value);
            if (subProduct == null)
            {
                return NotFound();
            }
            
            return View(subProduct);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name,ProductId,ProductsSubCategoryId,Price,IsSelectedOnDefault")]
            ProductsSubCategoryProductData subProductData)
        {
            var companyId = await _bll.Products.GetProductCompanyId(subProductData.ProductId);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
         
            var subProduct = await _bll.ProductsSubCategoryProducts.FirstOrDefaultAsync(subProductData.Id);
            if (subProduct == null)
            {
                return NotFound();
            }
            subProduct.Name = subProductData.Name;
            subProduct.Price = subProductData.Price;
            subProduct.IsSelectedOnDefault = subProductData.IsSelectedOnDefault;
            subProduct.Description = subProductData.Description;
            
            _bll.ProductsSubCategoryProducts.Update(subProduct);
            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(Edit), "Product", new {id = subProductData.ProductId});
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var companyId = await _bll.ProductsSubCategoryProducts.GetProductsSubCategoryProductCompanyId(id.Value);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            var subProduct = await _bll.ProductsSubCategoryProducts
                .FirstOrDefaultEditAsyncBLL(id.Value);
            if (subProduct == null)
            {
                return NotFound();
            }

            return View(subProduct);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subProduct = await _bll.ProductsSubCategoryProducts.FirstOrDefaultAsync(id);
            if (subProduct == null)
            {
                return NotFound();
            }
            
            var companyId = await _bll.ProductsSubCategoryProducts.GetProductsSubCategoryProductCompanyId(id);
            
            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }
            var productId = await _bll.ProductsSubCategoryProducts.GetProductId(id);
          
            await _bll.ProductsSubCategoryProducts.MoveSubCategoryProductsUpWhenDelete(id);

            _bll.ProductsSubCategoryProducts.Remove(subProduct);
            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(Edit), "Product", new {id = productId});
        }

        public async Task<IActionResult> MoveSubProduct(int id, bool moveUp)
        {
            var companyId = await _bll.ProductsSubCategoryProducts.GetProductsSubCategoryProductCompanyId(id);

            if (!await User.DoesUserHaveAuthorityToEdit(companyId, _userManager))
            {
                return NotFound();
            }

            if (!await _bll.ProductsSubCategoryProducts.ExistsAsync(id))
            {
                return NotFound();
            }

            if (!await _bll.ProductsSubCategoryProducts.ChangeSubCategoryProductPosition(id, moveUp))
            {
                return BadRequest();
            }
            
            var productId = await _bll.ProductsSubCategoryProducts.GetProductId(id);
            
            return RedirectToAction(nameof(Edit), "Product", new {id = productId});
        }
    }
}

WebApp/Areas/Admin/Views/Product/Create.cshtml
@model BLL.App.DTO.Product.ProductCreate

@{
    ViewData["Title"] = "Create";
}

<h1>@Resources.CommonCrud.Create</h1>

<h4>@Resources.BLL.App.DTO.Product.ProductString</h4>
<hr />
<div class="row">
        <form asp-action="Create">
            <input asp-for="MenuId" type="hidden">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control"/>
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAlwaysPurchasable"/> 
                    @Html.DisplayNameFor(model => model.IsAlwaysPurchasable)
                </label>
            </div>
            
            <div class="form-group">
                <label asp-for="MenuCategories" class="control-label"></label>
                <select asp-for="MenuCategoryId">
                    @foreach (var category in Model.MenuCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="@Resources.CommonCrud.Create" class="btn btn-primary"/>
            </div>
        </form>
</div>

<div>
    <a asp-controller="Menu" asp-action="Edit" asp-route-id="@Model.MenuId">@Resources.CommonCrud.BackToMenu</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Areas/Admin/Views/Product/Delete.cshtml
@model BLL.App.DTO.Product.ProductEdit

@{
    ViewData["Title"] = "Delete";
}

<h1>@Resources.CommonCrud.Delete</h1>

<h3>@Resources.CommonCrud.DeleteAreYouSureMessage</h3>
<div>
    <h4>@Resources.BLL.App.DTO.Product.ProductString</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAlwaysPurchasable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAlwaysPurchasable)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Resources.CommonCrud.Delete" class="btn btn-danger" /> |
        <a asp-controller="Menu" asp-action="Edit" asp-route-id="@Model.MenuId">@Resources.CommonCrud.BackToMenu</a>
    </form>
</div>

WebApp/Areas/Admin/Views/Product/Edit.cshtml
@model BLL.App.DTO.Product.ProductEdit

@{
    ViewData["Title"] = "Edit";
}

<h1>@Resources.CommonCrud.Edit</h1>

<h4>@Resources.BLL.App.DTO.Product.ProductString</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
            <input asp-for="MenuId" type="hidden">
            <input asp-for="Id" type="hidden">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control"/>
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAlwaysPurchasable"/> 
                    @Html.DisplayNameFor(model => model.IsAlwaysPurchasable)
                </label>
            </div>
                    
            @if(Model.MenuCategories != null){
                <div class="form-group">
                    <label asp-for="MenuCategories" class="control-label"></label>
                    <select asp-for="MenuCategoryId">
                        @foreach (var category in Model.MenuCategories)
                        {
                            <option
                                selected="@(Model.MenuCategoryId.Equals(category.Id) ? "selected" : null)"
                                value="@category.Id">@category.Name
                            </option>
                        }
                    </select>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="@Resources.CommonCrud.Save" class="btn btn-primary"/>
                <a asp-controller="Menu" asp-action="Edit" asp-route-id="@Model.MenuId">@Resources.CommonCrud.BackToMenu</a>
            </div>
            <hr>
        </form>
    </div>
    <div class="col-md">
        <h4>@Resources.BLL.App.DTO.ProductsSubCategory.ProductsSubCategories:</h4>
        <hr>
        <div style="text-align: right"><a asp-controller="SubCategory" asp-action="Create" asp-route-productId="@Model.Id">
                @Resources.CommonCrud.CreateNew @Resources.BLL.App.DTO.ProductsSubCategory.ProductsSubCategoryString
            </a>
        </div>
        @if (Model.ProductsSubCategories != null)
        {
            @for(var i = 0; i < Model.ProductsSubCategories.Count; i++)
            {
                <div>
                    <h5>
                        @Html.DisplayFor(x => Model.ProductsSubCategories[i].Name)
                        <span @Html.Raw(i.Equals(0) ? "hidden='hidden'" : "")>
                            |
                            <a asp-controller="SubCategory" asp-action="MoveCategory" asp-route-menuId="@Model.Id"
                               asp-route-id="@Model.ProductsSubCategories[i].Id" asp-route-moveUp="true">
                                @Resources.CommonCrud.Up
                            </a>
                        </span>
                        <span @Html.Raw(i.Equals(Model.ProductsSubCategories.Count - 1) ? "hidden='hidden'" : "")>
                            |
                            <a asp-controller="SubCategory" asp-action="MoveCategory" asp-route-menuId="@Model.Id"
                               asp-route-id="@Model.ProductsSubCategories[i].Id" asp-route-moveUp="false">
                                @Resources.CommonCrud.Down
                            </a>
                        </span>
                        |
                        <a asp-controller="SubCategory" asp-action="Edit"
                           asp-route-id="@Model.ProductsSubCategories[i].Id">@Resources.CommonCrud.Edit</a> |
                        <a asp-controller="SubCategory" asp-action="Delete"
                           asp-route-id="@Model.ProductsSubCategories[i].Id">@Resources.CommonCrud.Delete</a>
                    </h5>
                </div>
                <div>
                    @Html.DisplayNameFor(x => Model.ProductsSubCategories[i].MandatoryItemCount):
                    @Html.DisplayFor(x => Model.ProductsSubCategories[i].MandatoryItemCount)
                    |
                    @Html.DisplayNameFor(x => Model.ProductsSubCategories[i].MaxItemCount):
                    @Html.DisplayFor(x => Model.ProductsSubCategories[i].MaxItemCount)
                </div>
                if (Model.ProductsSubCategories[i].SubCategoryProducts != null)
                {
                    @for (var j = 0; j < Model.ProductsSubCategories[i].SubCategoryProducts!.Count; j++)
                    {
                        <div>
                            <h6>
                                @Html.DisplayFor(x => Model.ProductsSubCategories[i].SubCategoryProducts![j].Name)
                            </h6>
                            @Html.DisplayFor(x => Model.ProductsSubCategories[i].SubCategoryProducts![j].Price)
                            @Resources.CommonCrud.Currency
                            <span @Html.Raw(j.Equals(0) ? "hidden='hidden'" : "")>
                                |
                                <a asp-controller="SubProduct" asp-action="MoveSubProduct" asp-route-menuId="@Model.Id"
                                   asp-route-id="@Model.ProductsSubCategories[i].SubCategoryProducts![j].Id" asp-route-moveUp="true">
                                    @Resources.CommonCrud.Up
                                </a>
                            </span>
                            <span @Html.Raw(j.Equals(Model.ProductsSubCategories[i].SubCategoryProducts!.Count - 1) ? "hidden='hidden'" : "")>
                                |
                                <a asp-controller="SubProduct" asp-action="MoveSubProduct" asp-route-menuId="@Model.Id"
                                   asp-route-id="@Model.ProductsSubCategories[i].SubCategoryProducts![j].Id" asp-route-moveUp="false">
                                    @Resources.CommonCrud.Down
                                </a>
                            </span>
                            |
                            <a asp-controller="SubProduct" asp-action="Edit"
                               asp-route-id="@Model.ProductsSubCategories[i].SubCategoryProducts![j].Id">@Resources.CommonCrud.Edit</a> |
                            <a asp-controller="SubProduct" asp-action="Delete"
                               asp-route-id="@Model.ProductsSubCategories[i].SubCategoryProducts![j].Id">@Resources.CommonCrud.Delete</a>
                            <br/>
                            @Html.DisplayNameFor(x => Model.ProductsSubCategories[i].SubCategoryProducts![j].IsSelectedOnDefault)
                            @Html.DisplayFor(x => Model.ProductsSubCategories[i].SubCategoryProducts![j].IsSelectedOnDefault)
                            <br/>
                            @if (Model.ProductsSubCategories[i].SubCategoryProducts![j].Description != null)
                            {
                                <div>
                                    @Html.DisplayNameFor(x => Model.ProductsSubCategories[i].SubCategoryProducts![j].Description):
                                    @Html.DisplayFor(x => Model.ProductsSubCategories[i].SubCategoryProducts![j].Description)
                                </div>
                            }
                        </div>
                    }
                }
                <a asp-controller="SubProduct" asp-action="Create" asp-route-subCategoryId="@Model.ProductsSubCategories[i].Id">
                    @Resources.CommonCrud.CreateNew @Resources.BLL.App.DTO.ProductsSubCategoryProduct.ProductsSubCategoryProductString
                </a>
                <hr>
            }
        }
    </div>
    <hr />
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}