WebApp/Areas/Admin/Controllers/MenuController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Mappers;
using BLL.App.DTO.Menu;
using Contracts.BLL.App;
using Domain.App.Identity;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Company Admin")]
    public class MenuController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;

        public MenuController(UserManager<AppUser> userManager, IAppBLL bll)
        {
            _userManager = userManager;
            _bll = bll;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _bll.Menus.GetAllIndexASyncBLL(await _bll.AppUsers.GetUserCompanyId(User.GetUserId()!.Value)));
        }
        

        [Authorize(Roles = "Company Admin")]
        public async Task<IActionResult> Create()
        {
            var newMenu = new MenuData
            {
                CompanyId = (await _bll.AppUsers.GetUserCompanyId(User.GetUserId()!.Value))!.Value
            };
            return View(newMenu);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,CompanyId")] MenuData menu)
        {
            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                _bll.Menus.Add(MenuMapper.MapToRegBLL(menu));
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(menu);
        }

        public async Task<IActionResult> Edit(int? id, int? currentCategoryId)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            if (currentCategoryId != null && !await _bll.MenuCategories.ExistsAsync(currentCategoryId.Value))
            {
                return NotFound();
            }

            var menu = await _bll.Menus.FirstOrDefaultEditAsyncBLL(id.Value, currentCategoryId);
         
            if (menu == null)
            {
                return NotFound();
            }

            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }
            
            return View(menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int? currentCategoryId, string name)
        {
            var menu = await _bll.Menus.FirstOrDefaultAsync(id);

            if (menu == null)
            {
                return NotFound();
            }

            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }

            menu.Name = name;
            _bll.Menus.Update(menu);
            await _bll.SaveChangesAsync();

            return RedirectToAction(nameof(Edit), new {id, currentCategoryId});
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var menu = await _bll.Menus.FirstOrDefaultAsync(id.Value);
            if (menu == null)
            {
                return NotFound();
            }
            
            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }


            return View(menu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var menu = await _bll.Menus.FirstOrDefaultAsync(id);
            if (menu == null)
            {
                return NotFound();
            }

            if (!await User.DoesUserHaveAuthorityToEdit(menu.CompanyId, _userManager))
            {
                return NotFound();
            }

            _bll.Menus.Remove(menu);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> MoveCategory(int categoryId, int menuId, bool moveUp)
        {
            if (!await _bll.MenuCategories.ExistsAsync(categoryId))
            {
                return NotFound();
            }
            var categoryCompanyId = await _bll.MenuCategories.GetCategoryCompanyId(categoryId);
            if (!await User.DoesUserHaveAuthorityToEdit(categoryCompanyId, _userManager))
            {
                return NotFound();
            }
         
            var result = await _bll.MenuCategories.ChangeCategoryPosition(categoryId, moveUp);
            if (!result)
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Edit), new {id = menuId});

        }
        
        public async Task<IActionResult> CopyOtherMenuItems(int currentMenuId, int otherMenuId)
        {
            if (!await _bll.Menus.ExistsAsync(currentMenuId) && !await _bll.Menus.ExistsAsync(otherMenuId))
            {
                return NotFound();
            }
            
            var menuCompanyId = await _bll.Menus.GetMenuCompanyId(currentMenuId);
            var otherMenuCompanyId = await _bll.Menus.GetMenuCompanyId(otherMenuId);
            if (menuCompanyId != otherMenuCompanyId || !await User.DoesUserHaveAuthorityToEdit(menuCompanyId, _userManager))
            {
                return NotFound();
            }

            await _bll.Menus.CopyMenuItemsToOtherMenu(currentMenuId, otherMenuId);
            
            return RedirectToAction(nameof(Edit), new {id = currentMenuId});
        }
    }
}

WebApp/Areas/Admin/Controllers/RoleController.cs
#pragma warning disable 1591
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BLL.App.DTO.Identity;
using BLL.App.DTO.Mappers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {

        private readonly AppRoleMapper _appRoleMapper;
        private readonly RoleManager<Domain.App.Identity.AppRole> _roleManager;
        
        public RoleController(RoleManager<Domain.App.Identity.AppRole> roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _appRoleMapper = new AppRoleMapper(mapper);
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles
                .Select(r =>_appRoleMapper.Map(r))
                .ToListAsync();
            
            return View(roles);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string Name)
        {
            if (ModelState.IsValid)
            {
                var role = new Domain.App.Identity.AppRole
                {
                    Name = Name
                };
                await _roleManager.CreateAsync(role);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appRole = _appRoleMapper.Map(await _roleManager.Roles
                .FirstOrDefaultAsync(r => r.Id.Equals(id)));
            if (appRole == null)
            {
                return NotFound();
            }
            return View(appRole);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] AppRole appRole)
        {
            if (id != appRole.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var role = await _roleManager.Roles.FirstOrDefaultAsync(r => r.Id.Equals(id));
                if (role == null)
                {
                    return NotFound();
                }
                role.Name = appRole.Name;
                await _roleManager.UpdateAsync(role);
                return RedirectToAction(nameof(Index));
            }
            return View(appRole);
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appRole = _appRoleMapper.Map(await _roleManager.Roles
                .FirstOrDefaultAsync(r => r.Id.Equals(id)));
            if (appRole == null)
            {
                return NotFound();
            }

            return View(appRole);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appRole = await _roleManager.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            await _roleManager.DeleteAsync(appRole);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/BasketController.cs
#pragma warning disable 1591
using System;
using System.Threading.Tasks;
using BLL.App.DTO.Order;
using Contracts.BLL.App;
using Contracts.DAL.App;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace WebApp.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly IAppBLL _bll;
        
        public BasketController(IAppBLL bll)
        {
            _bll = bll;
        }
        
        public async Task<IActionResult> Index()
        {
            var userId = User.GetUserId()!.Value;
            await _bll.Orders.ReCalculateOrderCost(await _bll.Orders.GetUserBasketId(userId));
            var userBasket = await _bll.Orders.FirstOrDefaultClientAsyncBLL(userId);
            
            return View(userBasket);
        }

        [HttpPost]
        public async Task<IActionResult> SubmitOrder(string? cardNumber, bool payInRestaurant)
        {
            var orderId = await _bll.Orders.GetUserBasketId(User.GetUserId()!.Value);

            if (orderId == default)
            {
                return BadRequest();
            }
            
            if (payInRestaurant)
            {
                if (!await _bll.Orders.SubmitOrder(orderId, null))
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index), "Order");
            }

            if (cardNumber == null)
            {
                return RedirectToAction(nameof(Index));
            }
            
            if (!await _bll.Orders.SubmitOrder(orderId, cardNumber))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index), "Order");
        }

        [HttpPost]
        public async Task<IActionResult> AddCustomerComment(int orderId, string comment)
        {
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }
            
            if (!await _bll.Orders.AddCustomerCommentToOrder(User.GetUserId()!.Value, orderId, comment))
            {
                return NotFound();
            }
            
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangeProductAmountInOrder(int productInOrderId, int newAmount)
        {
            if (newAmount < 1)
            {
                return BadRequest();
            }
            
            if (!await _bll.ProductsInOrder.ExistsAsync(productInOrderId))
            {
                return NotFound();
            }
            
            var orderId = await _bll.ProductsInOrder.GetOrderId(productInOrderId);
            
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }
            
            if (!await _bll.ProductsInOrder.ChangeProductInOrderAmount(orderId, productInOrderId, newAmount))
            {
                return NotFound();
            }

            await _bll.Orders.ReCalculateOrderCost(orderId);
            
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        public async Task<IActionResult> RemoveProductFromOrder(int productInOrderId)
        {
            var productInOrder = await _bll.ProductsInOrder.FirstOrDefaultAsync(productInOrderId);
            if (productInOrder == null)
            {
                return NotFound();
            }
            
            var orderId = await _bll.ProductsInOrder.GetOrderId(productInOrderId);
            
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }

            _bll.ProductsInOrder.Remove(productInOrder);
            await _bll.SaveChangesAsync();

            if (await _bll.Orders.DeleteIfOrderIsEmpty(orderId))
            {
                return RedirectToAction(nameof(Index));
            }
            
            await _bll.Orders.ReCalculateOrderCost(orderId);

            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/OrderController.cs
#pragma warning disable 1591
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Domain.App.Identity;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
      
        private readonly IAppBLL _bll;
        private UserManager<AppUser> _userManager;
        
        public OrderController(IAppBLL bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            var orders = await _bll.Orders.GetAllActiveClientAsyncBLL(User.GetUserId()!.Value);

            return View(orders);
        }
        
        public async Task<IActionResult> Completed()
        {
            var orders = await _bll.ArchivedOrders.GetAllCompletedOrdersClientAsyncBLL(User.GetUserId()!.Value);

            return View(orders);
        }
        
        public async Task<IActionResult> AddCommentToArchivedOrder(int orderId, string comment)
        {
            if (!await _bll.ArchivedOrders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }

            await _bll.ArchivedOrders.AddCommentToOrder(orderId, comment, true);

            return RedirectToAction(nameof(Completed));
        }
        
        public async Task<IActionResult> AddRatingToOrder(int orderId, int rating)
        {
            if (rating < 1 || rating > 5)
            {
                return BadRequest();
            }
            
            if (!await _bll.ArchivedOrders.ExistsAsync(orderId))
            {
                return NotFound();
            }
            
            if (!await _bll.Orders.DoesOrderBelongToCustomer(User.GetUserId()!.Value, orderId))
            {
                return BadRequest();
            }

            await _bll.ArchivedOrders.AddRatingToOrder(orderId, rating);
            
            return RedirectToAction(nameof(Completed));
        }
    }
}

WebApp/Views/Shared/_LanguageSelection.cshtml
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder
@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new{Value = c.Name, Text = c.NativeName}).ToList();
}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @Resources.Views.Shared._Layout.Languages
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        @foreach (var item in cultureItems)
        {
            <a class="dropdown-item text-dark" asp-area="" asp-controller="Home" asp-action="SetLanguage" 
               asp-route-culture="@item.Value" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">@item.Text</a>
        }
    </div>
</li>

WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Domain.App.Identity
@using System.Security.Claims
@inject SignInManager<AppUser> _signInManager
@inject UserManager<AppUser> _userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Resources.Views.Shared._Layout.WebApp</a>
            @* <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
            @*         aria-expanded="false" aria-label="Toggle navigation"> *@
            @*     <span class="navbar-toggler-icon"></span> *@
            @* </button> *@
           
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Resources.Views.Shared._Layout.Users
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">@Resources.Views.Shared._Layout.Users</a>
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Role" asp-action="Index">@Resources.Views.Shared._Layout.Roles</a>
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">@Resources.Views.Shared._Layout.Companies</a>
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Restaurant" asp-action="Index">@Resources.Views.Shared._Layout.Restaurants</a>
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Menu" asp-action="Index">@Resources.Views.Shared._Layout.Menus</a>
                            </div>
                        </li>
                    }
                    @if (User.IsInRole("Company Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">@Resources.Views.Shared._Layout.Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="CompanyAdmin" asp-controller="Company" asp-action="Index">@Resources.Views.Shared._Layout.Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="CompanyAdmin" asp-controller="Restaurant" asp-action="Index">@Resources.Views.Shared._Layout.Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Menu" asp-action="Index">@Resources.Views.Shared._Layout.Menus</a>
                        </li>
                    }
                    @if (User.IsInRole("Restaurant Worker"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Worker" asp-controller="Restaurant" asp-action="Index">@Resources.Views.Shared._Layout.Orders</a>
                    </li>
                    }
                    
                    
                </ul>
                @if (_signInManager.IsSignedIn(User) && ((ClaimsIdentity) User.Identity!).Claims.All(c => c.Type != ClaimTypes.Role))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @Resources.Views.Shared._Layout.MyOrders
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-controller="Order" asp-action="Index">@Resources.Views.Shared._Layout.ActiveOrders</a>
                                    <a class="nav-link text-dark" asp-controller="Order" asp-action="Completed">@Resources.Views.Shared._Layout.CompletedOrders</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Basket" asp-action="Index">@Resources.Views.Shared._Layout.MyBasket</a>
                            </li>
                        </ul>
                }
                <ul class="navbar-nav">
                    <partial name="_LoginPartial"/>
                    <partial name="_LanguageSelection"/>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - @Resources.Views.Shared._Layout.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Resources.Views.Shared._Layout.Privacy</a>
        @(DateTime.Now.ToShortDateString())
        @(123.45.ToString())
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>